/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6
    },
    children: [
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_dept',
        path: '/manage/dept',
        component: 'view.manage_dept',
        meta: {
          title: 'manage_dept',
          i18nKey: 'route.manage_dept'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_post',
        path: '/manage/post',
        component: 'view.manage_post',
        meta: {
          title: 'manage_post',
          i18nKey: 'route.manage_post'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_tenant',
        path: '/manage/tenant',
        component: 'view.manage_tenant',
        meta: {
          title: 'manage_tenant',
          i18nKey: 'route.manage_tenant'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      order: 8
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          order: 1
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          order: 2
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'workflow',
    path: '/workflow',
    component: 'layout.base',
    meta: {
      title: 'workflow',
      i18nKey: 'route.workflow'
    },
    children: [
      {
        name: 'workflow_designer',
        path: '/workflow/designer',
        meta: {
          title: 'workflow_designer',
          i18nKey: 'route.workflow_designer'
        },
        children: [
          {
            name: 'workflow_designer_create',
            path: '/workflow/designer/create',
            component: 'view.workflow_designer_create',
            meta: {
              title: 'workflow_designer_create',
              i18nKey: 'route.workflow_designer_create'
            }
          }
        ]
      },
      {
        name: 'workflow_workspace',
        path: '/workflow/workspace',
        meta: {
          title: 'workflow_workspace',
          i18nKey: 'route.workflow_workspace'
        },
        children: [
          {
            name: 'workflow_workspace_about',
            path: '/workflow/workspace/about',
            component: 'view.workflow_workspace_about',
            meta: {
              title: 'workflow_workspace_about',
              i18nKey: 'route.workflow_workspace_about'
            }
          },
          {
            name: 'workflow_workspace_apply',
            path: '/workflow/workspace/apply',
            component: 'view.workflow_workspace_apply',
            meta: {
              title: 'workflow_workspace_apply',
              i18nKey: 'route.workflow_workspace_apply'
            }
          },
          {
            name: 'workflow_workspace_approval',
            path: '/workflow/workspace/approval',
            component: 'view.workflow_workspace_approval',
            meta: {
              title: 'workflow_workspace_approval',
              i18nKey: 'route.workflow_workspace_approval'
            }
          },
          {
            name: 'workflow_workspace_done',
            path: '/workflow/workspace/done',
            component: 'view.workflow_workspace_done',
            meta: {
              title: 'workflow_workspace_done',
              i18nKey: 'route.workflow_workspace_done'
            }
          },
          {
            name: 'workflow_workspace_todo',
            path: '/workflow/workspace/todo',
            component: 'view.workflow_workspace_todo',
            meta: {
              title: 'workflow_workspace_todo',
              i18nKey: 'route.workflow_workspace_todo'
            }
          }
        ]
      }
    ]
  }
];
